# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7k325tffg900-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/oe/Downloads/xillybus-eval-kintex7-1.2d/verilog/vivado/xillydemo.cache/wt [current_project]
set_property parent.project_path /home/oe/Downloads/xillybus-eval-kintex7-1.2d/verilog/vivado/xillydemo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip /home/oe/Downloads/xillybus-eval-kintex7-1.2d/vivado-essentials/pcie_k7_vivado/pcie_k7_vivado.xci
set_property used_in_synthesis false [get_files -all /home/oe/Downloads/xillybus-eval-kintex7-1.2d/vivado-essentials/pcie_k7_vivado/example_design/xilinx_pcie_7x_ep_x8g1_KC705_REVC.xdc]
set_property used_in_implementation false [get_files -all /home/oe/Downloads/xillybus-eval-kintex7-1.2d/vivado-essentials/pcie_k7_vivado/example_design/xilinx_pcie_7x_ep_x8g1_KC705_REVC.xdc]
set_property is_locked true [get_files /home/oe/Downloads/xillybus-eval-kintex7-1.2d/vivado-essentials/pcie_k7_vivado/pcie_k7_vivado.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file pcie_k7_vivado.hwdef }
synth_design -top pcie_k7_vivado -part xc7k325tffg900-2 -mode out_of_context
rename_ref -prefix_all pcie_k7_vivado_
write_checkpoint -noxdef pcie_k7_vivado.dcp
catch { report_utilization -file pcie_k7_vivado_utilization_synth.rpt -pb pcie_k7_vivado_utilization_synth.pb }
if { [catch {
  file copy -force /home/oe/Downloads/xillybus-eval-kintex7-1.2d/verilog/vivado/xillydemo.runs/pcie_k7_vivado_synth_1/pcie_k7_vivado.dcp /home/oe/Downloads/xillybus-eval-kintex7-1.2d/vivado-essentials/pcie_k7_vivado/pcie_k7_vivado.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /home/oe/Downloads/xillybus-eval-kintex7-1.2d/vivado-essentials/pcie_k7_vivado/pcie_k7_vivado_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /home/oe/Downloads/xillybus-eval-kintex7-1.2d/vivado-essentials/pcie_k7_vivado/pcie_k7_vivado_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /home/oe/Downloads/xillybus-eval-kintex7-1.2d/vivado-essentials/pcie_k7_vivado/pcie_k7_vivado_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /home/oe/Downloads/xillybus-eval-kintex7-1.2d/vivado-essentials/pcie_k7_vivado/pcie_k7_vivado_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
